# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 21:00
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MaintainerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MaintananceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referenceNumber', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Plumbing', 'Plumbing'), ('Electrical', 'Electrical'), ('Security', 'Security')], max_length=30)),
                ('status', models.CharField(choices=[('New', 'New'), ('Acknowledged', 'Acknowledged'), ('In Progress', 'In Progress'), ('AwaitingUserSignoff', 'AwaitingUserSignoff'), ('Complete', 'Complete'), ('Close', 'Close')], max_length=10)),
                ('description', models.TextField()),
                ('picture', models.ImageField(blank=True, upload_to='maintenancerequests/')),
                ('datelogged', models.DateTimeField(auto_now_add=True)),
                ('expirationdate', models.DateTimeField(default=datetime.datetime(2016, 10, 2, 21, 0, 51, 18062))),
                ('maintainerId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manager.Maintainer')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personnelNumber', models.CharField(blank=True, max_length=30)),
                ('idNumber', models.CharField(max_length=13)),
                ('cellphone', models.CharField(max_length=10)),
                ('residence', models.CharField(max_length=30)),
                ('roomNumber', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ResidenceMaintainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Residence')),
            ],
        ),
        migrations.AddField(
            model_name='maintanancerequest',
            name='residence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Residence'),
        ),
        migrations.AddField(
            model_name='maintanancerequest',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintainer',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.MaintainerType'),
        ),
    ]
