# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 20:06
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MaintainerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MaintananceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referenceNumber', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Plumbing', 'Plumbing'), ('Electrical', 'Electrical'), ('Security', 'Security')], default=1, max_length=10)),
                ('status', models.CharField(choices=[('New', 'New'), ('Acknowledged', 'Acknowledged'), ('In Progress', 'In Progress'), ('AwaitingUserSignoff', 'AwaitingUserSignoff'), ('Complete', 'Complete')], default=1, max_length=10)),
                ('description', models.TextField()),
                ('datelogged', models.DateTimeField(auto_now_add=True)),
                ('expirationdate', models.DateTimeField(default=datetime.datetime(2016, 9, 29, 20, 6, 2, 830728))),
                ('maintainerId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manager.Maintainer')),
                ('userid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentNumber', models.CharField(blank=True, max_length=30)),
                ('idNumber', models.CharField(max_length=30)),
                ('cellphone', models.CharField(max_length=30)),
                ('residence', models.CharField(max_length=30)),
                ('roomNumber', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='maintainer',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.MaintainerType'),
        ),
    ]
