# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 21:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintanancerequest',
            name='expirationdate',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 2, 21, 3, 1, 3126)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='residence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Residence'),
        ),
    ]
