# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 19:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Incident',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
