# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 16:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20160930_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintanancerequest',
            name='expirationdate',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 7, 16, 45, 7, 165581)),
        ),
        migrations.AlterField(
            model_name='maintanancerequest',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Acknowledged', 'Acknowledged'), ('In Progress', 'In Progress'), ('AwaitingUserSignoff', 'AwaitingUserSignoff'), ('Complete', 'Complete'), ('Close', 'Close')], max_length=30),
        ),
    ]
